apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  namespace: video-to-mp3
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: saikumar134888/converter:python3.10-v2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            exec:
              command: ["pgrep", "python"]
            initialDelaySeconds: 10
            periodSeconds: 30

          readinessProbe:
            exec:
              command: ["pgrep", "python"]
            initialDelaySeconds: 5
            periodSeconds: 15

      securityContext:
        runAsNonRoot: true