apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: video-to-mp3
  labels:
    app: mysql
spec:
  clusterIP: None  # Headless service
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
