apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
    app.kubernetes.io/name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auth
        app.kubernetes.io/name: auth
    spec:
      containers:
        - name: auth
          image: saikumar134888/auth:python3.10-v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
