apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: video-to-mp3
  labels:
    app: auth
    app.kubernetes.io/name: auth
type: Opaque
stringData:
  MYSQL_PASSWORD: auth123
  JWT_SECRET: secret
