apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
    app.kubernetes.io/name: auth
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
