apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: video-to-mp3
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog
          imagePullPolicy: Always
          ports:
            - containerPort: 1025  # SMTP
            - containerPort: 8025  # Web UI
