apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: video-to-mp3
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025
  type: NodePort  # So you can access web UI from outside (optional)
