apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: video-to-mp3
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: notification
    spec:
      restartPolicy: Always
      containers:
        - name: notification
          image: saikumar134888/notification:python3.10-v2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            exec:
              command: ["pgrep", "python"]
            initialDelaySeconds: 10
            periodSeconds: 30

          readinessProbe:
            exec:
              command: ["pgrep", "python"]
            initialDelaySeconds: 5
            periodSeconds: 15

      securityContext:
        runAsNonRoot: true
