apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: video-to-mp3
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      type: Container

#  This ensures if any pod does not specify resources, it will automatically get the above defaults.
