apiVersion: v1
kind: ResourceQuota
metadata:
  name: video-to-mp3-quota
  namespace: video-to-mp3
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "20"
    persistentvolumeclaims: "7"

#This restricts the total usage across the namespace to avoid runaway consumption.
